version: "3.5"

services:
  mancala-app:
    build: .
    container_name: mancala-app
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=mancala
      - DB_USER=postgres
      - DB_PASS=postgres

  db:
    image: 'postgres:15-alpine'
    container_name: mancala-app-db
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - mancala-app-db-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mancala

networks:
  backend:

volumes:
  mancala-app-db-vol:
    external: false
