---
server.http2.enabled: true
app:
  appName: "Online Mancala Game"

spring:
  main:
    banner-mode: console
    banner:
      location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:mancala}"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      minimumIdle: 3
      maximumPoolSize: 10
      connectionTimeout: 15000
      validationTimeout: 1000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  config: classpath:logback-spring.xml
